// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: apis/contrib.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contrib struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	User       string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Date       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Repository string                 `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	// Types that are assignable to ContribType:
	//
	//	*Contrib_Approve
	//	*Contrib_Comment
	ContribType isContrib_ContribType `protobuf_oneof:"contrib_type"`
}

func (x *Contrib) Reset() {
	*x = Contrib{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_contrib_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contrib) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contrib) ProtoMessage() {}

func (x *Contrib) ProtoReflect() protoreflect.Message {
	mi := &file_apis_contrib_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contrib.ProtoReflect.Descriptor instead.
func (*Contrib) Descriptor() ([]byte, []int) {
	return file_apis_contrib_proto_rawDescGZIP(), []int{0}
}

func (x *Contrib) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contrib) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Contrib) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Contrib) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (m *Contrib) GetContribType() isContrib_ContribType {
	if m != nil {
		return m.ContribType
	}
	return nil
}

func (x *Contrib) GetApprove() string {
	if x, ok := x.GetContribType().(*Contrib_Approve); ok {
		return x.Approve
	}
	return ""
}

func (x *Contrib) GetComment() string {
	if x, ok := x.GetContribType().(*Contrib_Comment); ok {
		return x.Comment
	}
	return ""
}

type isContrib_ContribType interface {
	isContrib_ContribType()
}

type Contrib_Approve struct {
	Approve string `protobuf:"bytes,5,opt,name=approve,proto3,oneof"`
}

type Contrib_Comment struct {
	Comment string `protobuf:"bytes,6,opt,name=comment,proto3,oneof"`
}

func (*Contrib_Approve) isContrib_ContribType() {}

func (*Contrib_Comment) isContrib_ContribType() {}

type ListContribsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	PageSize   int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken  string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (x *ListContribsRequest) Reset() {
	*x = ListContribsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_contrib_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListContribsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContribsRequest) ProtoMessage() {}

func (x *ListContribsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_contrib_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContribsRequest.ProtoReflect.Descriptor instead.
func (*ListContribsRequest) Descriptor() ([]byte, []int) {
	return file_apis_contrib_proto_rawDescGZIP(), []int{1}
}

func (x *ListContribsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ListContribsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListContribsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListContribsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contribs      []*Contrib `protobuf:"bytes,1,rep,name=contribs,proto3" json:"contribs,omitempty"`
	NextPageToken string     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ListContribsResponse) Reset() {
	*x = ListContribsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_contrib_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListContribsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContribsResponse) ProtoMessage() {}

func (x *ListContribsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_contrib_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContribsResponse.ProtoReflect.Descriptor instead.
func (*ListContribsResponse) Descriptor() ([]byte, []int) {
	return file_apis_contrib_proto_rawDescGZIP(), []int{2}
}

func (x *ListContribsResponse) GetContribs() []*Contrib {
	if x != nil {
		return x.Contribs
	}
	return nil
}

func (x *ListContribsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_apis_contrib_proto protoreflect.FileDescriptor

var file_apis_contrib_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69,
	0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x07, 0x61, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x71, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x64, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x69, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69,
	0x62, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x47, 0x0a, 0x08, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x69, 0x62, 0x73, 0x12, 0x3b, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x69, 0x62, 0x73, 0x12, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x69, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x6f, 0x6b, 0x61, 0x6d, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_apis_contrib_proto_rawDescOnce sync.Once
	file_apis_contrib_proto_rawDescData = file_apis_contrib_proto_rawDesc
)

func file_apis_contrib_proto_rawDescGZIP() []byte {
	file_apis_contrib_proto_rawDescOnce.Do(func() {
		file_apis_contrib_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_contrib_proto_rawDescData)
	})
	return file_apis_contrib_proto_rawDescData
}

var file_apis_contrib_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apis_contrib_proto_goTypes = []interface{}{
	(*Contrib)(nil),               // 0: Contrib
	(*ListContribsRequest)(nil),   // 1: ListContribsRequest
	(*ListContribsResponse)(nil),  // 2: ListContribsResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_apis_contrib_proto_depIdxs = []int32{
	3, // 0: Contrib.date:type_name -> google.protobuf.Timestamp
	0, // 1: ListContribsResponse.contribs:type_name -> Contrib
	1, // 2: Contribs.ListContribs:input_type -> ListContribsRequest
	2, // 3: Contribs.ListContribs:output_type -> ListContribsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apis_contrib_proto_init() }
func file_apis_contrib_proto_init() {
	if File_apis_contrib_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_contrib_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contrib); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_contrib_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListContribsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_contrib_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListContribsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_apis_contrib_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Contrib_Approve)(nil),
		(*Contrib_Comment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_contrib_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_contrib_proto_goTypes,
		DependencyIndexes: file_apis_contrib_proto_depIdxs,
		MessageInfos:      file_apis_contrib_proto_msgTypes,
	}.Build()
	File_apis_contrib_proto = out.File
	file_apis_contrib_proto_rawDesc = nil
	file_apis_contrib_proto_goTypes = nil
	file_apis_contrib_proto_depIdxs = nil
}
