name: Protocol Buffers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: make proto
      - run: git diff --exit-code
