name: Protocol Buffers

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-${{ hashFiles('**/Makefile') }}
      - run: make proto
      - run: git diff --exit-code
